import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { SessionProviders } from '@/components/session-provider/page'
import DesignerContextProvder from '@/components/context/DesignerContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DesignerContextProvder>
        <SessionProviders>
        {children}
        </SessionProviders>
        </DesignerContextProvder>
      </body>
    </html>
  )
}
